spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.101.190.84:3306/yjx?useUnicode=true&characterEncoding=utf-8&serverTimezone=CTT
      username: root
      password: hj123456
# 最小连接池数量
      min-idle: 5
# 最大连接池数量
      max-active: 30
# 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
# 初始化时建立物理连接的个数
      initial-size: 5
# 连接保持空闲而不被驱逐的最小时间
      min-evictable-idle-time-millis: 300000
# 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
# 用来检测连接是否有效的sql，要求是一个查询语句
      validation-query: SELECT 1 FROM DUAL
# 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
# 获取连接时最大等待时间，单位毫秒
      max-wait: 60000
# 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
      max-pool-prepared-statement-per-connection-size: 50
# 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-borrow: false
# 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      pool-prepared-statements: true
# 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-return: false
      filter:
        stat:
          # 开启慢查询
          mergeSql: true
          # 慢SQL记录超过5秒的sql在druid SQL控制台标红
          slowSqlMillis: 3000
        wall:
          enabled: false
        commons-log:
          enabled: false
        log4j:
          connection-log-enabled: false
        slf4j:
          statement-log-enabled: false
        log4j2:
          statement-log-enabled: false
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙 如果项目用的logback则删掉log4j
      filters: stat,wall
      # 配置Druid Spring监控切面
      aop-patterns: com.dw.controller.*,com.dw.ampq.*,com.dw.dao.mapper.*
      # 配置DruidStatFilter
      web-stat-filter:
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # 配置DruidStatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        reset-enable: true
        login-username: admin
        login-password: 123
  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 100MB

logging:
  config: classpath:pro-logback.xml


name: eduWebPro